In [1]:
import kagglehub
import pandas as pd
import numpy as np

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# 01. Leitura do Dataset

In [2]:
# Download latest version
path = kagglehub.dataset_download("ranafayezz/titanic-cleaned")

df_train = pd.read_csv(path+"/train_data.csv")
df_test = pd.read_csv(path+"/test_data.csv")

# 02. Análise Exploratória

In [3]:
df_train.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,0,1,0,1,0.2750,0.014151,0,0,1,0.1,1,0,0,0,0,0,1
1,1,2,1,0,0.4750,0.139136,1,0,0,0.1,1,0,0,0,1,0,0
2,2,3,1,0,0.3250,0.015469,0,0,1,0.0,0,0,0,1,0,0,1
3,3,4,1,0,0.4375,0.103644,1,0,0,0.1,1,0,0,0,0,0,1
4,4,5,0,1,0.4375,0.015713,0,0,1,0.0,1,0,0,0,0,0,1

In [4]:
df_train.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
count,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000
mean,395.500000,396.500000,0.386364,0.647727,0.368244,0.064677,0.243687,0.208333,0.547980,0.088636,0.744949,0.005051,0.040404,0.209596,0.185606,0.092172,0.720960
std,228.774999,228.774999,0.487223,0.477980,0.162994,0.100987,0.429577,0.406373,0.498007,0.154485,0.436165,0.070932,0.197029,0.407277,0.389034,0.289451,0.448811
min,0.000000,1.000000,0.000000,0.000000,0.008375,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,197.750000,198.750000,0.000000,0.000000,0.275000,0.015469,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,395.500000,396.500000,0.000000,1.000000,0.350000,0.028302,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,593.250000,594.250000,1.000000,1.000000,0.437500,0.061045,0.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,791.000000,792.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# 03. Construção do exercício

In [6]:
# Vou gerar uma variável qualitativa ordinal a partir das colunas
# `Pclass_1`, `Pclass_2`, e `Pclass_3` (qualitativas nominais)
df_train['Pclass'] = df_train['Pclass_1'] + 2*df_train['Pclass_2'] + 3*df_train['Pclass_3']

In [7]:
# Para fins desse exercício, vou escolher três variáveis explicativas:
var_explicativas = [
    "Age",  # Quantitativa discreta
    "Pclass",  # Qualitativa ordinal
    "Sex",  # Qualitativa nominal
]

df_X = df_train[var_explicativas]
df_y = df_train["Survived"]

def calculate_gini(y):
    """
    Calcula a impureza Gini de um vetor de labels (Target).
    Exemplo de uso: calculate_gini(df_train['Survived'])
    """
    n = len(y)
    if n == 0:
        return 0
        
    gini = 1.0
    for i in y.unique():
        prob = np.sum(y == i) / n
        gini -= prob ** 2
        
    return gini

# 04. Geração da stump

In [14]:
df_train.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3,Pclass
count,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000,792.000000
mean,395.500000,396.500000,0.386364,0.647727,0.368244,0.064677,0.243687,0.208333,0.547980,0.088636,0.744949,0.005051,0.040404,0.209596,0.185606,0.092172,0.720960,2.304293
std,228.774999,228.774999,0.487223,0.477980,0.162994,0.100987,0.429577,0.406373,0.498007,0.154485,0.436165,0.070932,0.197029,0.407277,0.389034,0.289451,0.448811,0.836634
min,0.000000,1.000000,0.000000,0.000000,0.008375,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,197.750000,198.750000,0.000000,0.000000,0.275000,0.015469,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,395.500000,396.500000,0.000000,1.000000,0.350000,0.028302,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000
75%,593.250000,594.250000,1.000000,1.000000,0.437500,0.061045,0.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000
max,791.000000,792.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000

In [15]:
# Calcular impureza das stumps com variáveis categóricas
gini_sex_0 = calculate_gini(df_train.loc[df_train['Sex'] == 0, "Survived"])
gini_sex_1 = calculate_gini(df_train.loc[df_train['Sex'] == 1, "Survived"])
gini_split_sex = (gini_sex_0 * len(df_train.loc[df_train['Sex'] == 0]) + gini_sex_1 * len(df_train.loc[df_train['Sex'] == 1])) / len(df_train)

gini_Pclass_1 = calculate_gini(df_train.loc[df_train['Pclass'] == 1, "Survived"])
gini_Pclass_2 = calculate_gini(df_train.loc[df_train['Pclass'] == 2, "Survived"])
gini_Pclass_3 = calculate_gini(df_train.loc[df_train['Pclass'] == 3, "Survived"])
gini_split_Pclass = (
        gini_Pclass_1 * len(df_train.loc[df_train['Pclass'] == 1]) +
        gini_Pclass_2 * len(df_train.loc[df_train['Pclass'] == 2]) +
        gini_Pclass_3 * len(df_train.loc[df_train['Pclass'] == 3])
    ) / len(df_train)

In [ ]:
# Calcular impureza da stump de variável quantitativa

# Primeiro passo é definir qual é o melhor threshold dessa variável.
# Para isso vou ordenar o data frame por ela (para visualização), e 
# calcular a quantidade de sobreviventes e casualidades para cada valor da
# variável, e em seguida aplicar o mesmo cálculo de Gini e obter o melhor threshold
df_age = df_train[['Age', 'Survived']].sort_values('Age')

# Gini do grupo 'less equal than'
df_age['gini_le'] = df_age.apply(
    lambda row: 
        calculate_gini(df_age.loc[df_age['Age'] <= row['Age'], 'Survived']),
    axis=1
)

# Gini do grupo 'greater than
df_age['gini_g'] = df_age.apply(
    lambda row: 
        calculate_gini(df_age.loc[df_age['Age'] > row['Age'], 'Survived']),
    axis=1
)

# Calcular também o tamanho dos grupos
df_age['len_threshold_le'] = df_age.apply(
    lambda row:
        len(df_age.loc[df_age['Age'] <= row['Age']]),
    axis=1
)
df_age['len_threshold_g'] = df_age.apply(
    lambda row:
        len(df_age.loc[df_age['Age'] > row['Age']]),
    axis=1
)

# Calcular gini para cada threshold
df_age['gini'] = (df_age['gini_le'] * df_age['len_threshold_le'] + df_age['gini_g'] * df_age['len_threshold_g']) / len(df_age)
best_threshold = df_age.loc[df_age['gini'] == df_age['gini'].min(), 'Age'].iloc[0]
gini_split_age = df_age.loc[df_age['Age'] == best_threshold, 'gini'].iloc[0]

In [ ]:
gini_split_age

np.float64(0.46197412959381046)

In [16]:
gini_split_Pclass

np.float64(0.42287595930683164)

In [17]:
gini_split_sex

np.float64(0.33105087217518836)

In [ ]:
# Agora, podemos descobrir qual variável explicativa melhor discrimina a variável target
# e defini-la como nossa stump