In [2]:
import kagglehub
import pandas as pd
import numpy as np

# 01. Dataset download

In [3]:
# Download latest version
path = kagglehub.dataset_download("mikhail1681/walmart-sales")

df = pd.read_csv(path + "/Walmart_Sales.csv")

In [4]:
df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   str
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), str(1)
memory usage: 402.3 KB

In [6]:
df.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

In [7]:
# Definição de parâmetros e objetivo (novamente, não vou aplicar nenhuma estratégia de validação
# pois a ideia do exercício é apenas mostrar o processo de treinamento do modelo, e não a avaliação de sua performance)
df_s1 = df.loc[df["Store"] == 1]

X = df_s1.drop(columns=["Weekly_Sales", "Date"])
y = df_s1["Weekly_Sales"]

# 02. Multiple Linear Regression (MLR)

In [8]:
# Inicializar pesos (aleatórios inicialmente)
weights = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]

# Inicializar bias
b = 0

# Passo de aprendizado
learning_rate = 0.0001

In [9]:
# Cálculo da predição inicial
y_pred = X.dot(weights) + b

# Sum of squared errors
sum_squared_error = ((y_pred - y) ** 2).sum()

sum_squared_error

np.float64(348883967966088.75)

In [24]:
# Cálculo do vetor gradiente

# Primeiro vou converter minhas variáveis em arrays do numpy para facilitar a manipulação
np_X = np.array(X)
np_weights = np.array(weights).reshape(-1, 1) 
np_y = np.array(y).reshape(-1, 1)

# Agora vou iniciar o cálculo do vetor gradiente
# O vetor gradiente é um vetor com os valores das derivadas parciais da função erro em relação a cada peso

# A derivada parcial de qualquer peso se dá por 2 * x_n * ((soma de a_i * x_i) + b - y_i)
# Sabendo que `((soma de a_i * x_i) + b - y_i)` é o erro, podemos simplificar a expressão para 2 * x_n * erro

# Vou primeiro calcular o erro de cada observação
np_erro = np_X @ np_weights + b - np_y

# Agora, calcular a soma do valor da derivada parcial de cada peso
np_gradiente = 2 * np_X.T @  np_erro

# Por fim, calcular a média do valor da derivada parcial de cada peso.
# Esse valor é o que "aumenta/reduz" ao máximo o erro da função de custo
np_gradiente = np_gradiente / len(y)

# Por fim, calcular o gradiente do intercept, cuja derivada é igual a 2 * ((soma de a_i * x_i) + b - y_i), ou 2 * erro
# e que, portanto, será igual a (2 * erro) / len(y), ou 2 * erro médio
np_gradiente_bias = 2 * np.mean(np_erro)

In [25]:
# Atualizar os parâmetros do modelo (pesos e bias) com base no vetor gradiente
np_weights -= learning_rate * np_gradiente
b -= learning_rate * np_gradiente[0]

# 03. Iteração

In [36]:
# Inicializar pesos (aleatórios inicialmente)
weights = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]

# Inicializar bias
b = 0

# Passo de aprendizado
learning_rate = 0.03

In [37]:
for epoch in range(500):
    # Cálculo da predição
    y_pred = X.dot(weights) + b

    # Sum of squared errors
    sum_squared_error = ((y_pred - y) ** 2).sum()
    print(f"Epoch {(epoch + 1):03d}: Mean of Squared Errors = {(sum_squared_error / len(y)):.2e}")

    # Cálculo do vetor gradiente

    # Primeiro vou converter minhas variáveis em arrays do numpy para facilitar a manipulação
    np_X = np.array(X)
    np_weights = np.array(weights).reshape(-1, 1) 
    np_y = np.array(y).reshape(-1, 1)

    # Agora vou iniciar o cálculo do vetor gradiente
    # O vetor gradiente é um vetor com os valores das derivadas parciais da função erro em relação a cada peso

    # A derivada parcial de qualquer peso se dá por 2 * x_n * ((soma de a_i * x_i) + b - y_i)
    # Sabendo que `((soma de a_i * x_i) + b - y_i)` é o erro, podemos simplificar a expressão para 2 * x_n * erro

    # Vou primeiro calcular o erro de cada observação
    np_erro = np_X @ np_weights + b - np_y

    # Agora, calcular a soma do valor da derivada parcial de cada peso
    np_gradiente = 2 * np_X.T @  np_erro

    # Por fim, calcular a média do valor da derivada parcial de cada peso.
    # Esse valor é o que "aumenta/reduz" ao máximo o erro da função de custo
    np_gradiente = np_gradiente / len(y)

    # Por fim, calcular o gradiente do intercept, cuja derivada é igual a 2 * ((soma de a_i * x_i) + b - y_i), ou 2 * erro
    # e que, portanto, será igual a (2 * erro) / len(y), ou 2 * erro médio
    np_gradiente_bias = 2 * np.mean(np_erro)

    # Atualizar os parâmetros do modelo (pesos e bias) com base no vetor gradiente
    np_weights -= learning_rate * np_gradiente
    b -= learning_rate * np_gradiente[0]

Epoch 001: Mean of Squared Errors = 2.44e+12
Epoch 002: Mean of Squared Errors = 2.16e+12
Epoch 003: Mean of Squared Errors = 1.91e+12
Epoch 004: Mean of Squared Errors = 1.69e+12
Epoch 005: Mean of Squared Errors = 1.50e+12
Epoch 006: Mean of Squared Errors = 1.33e+12
Epoch 007: Mean of Squared Errors = 1.17e+12
Epoch 008: Mean of Squared Errors = 1.04e+12
Epoch 009: Mean of Squared Errors = 9.22e+11
Epoch 010: Mean of Squared Errors = 8.17e+11
Epoch 011: Mean of Squared Errors = 7.25e+11
Epoch 012: Mean of Squared Errors = 6.43e+11
Epoch 013: Mean of Squared Errors = 5.71e+11
Epoch 014: Mean of Squared Errors = 5.08e+11
Epoch 015: Mean of Squared Errors = 4.51e+11
Epoch 016: Mean of Squared Errors = 4.02e+11
Epoch 017: Mean of Squared Errors = 3.58e+11
Epoch 018: Mean of Squared Errors = 3.19e+11
Epoch 019: Mean of Squared Errors = 2.85e+11
Epoch 020: Mean of Squared Errors = 2.54e+11
Epoch 021: Mean of Squared Errors = 2.27e+11
Epoch 022: Mean of Squared Errors = 2.04e+11
Epoch 023: Mean of Squared Errors = 1.83e+11
Epoch 024: Mean of Squared Errors = 1.64e+11
Epoch 025: Mean of Squared Errors = 1.48e+11
Epoch 026: Mean of Squared Errors = 1.34e+11
Epoch 027: Mean of Squared Errors = 1.21e+11
Epoch 028: Mean of Squared Errors = 1.10e+11
Epoch 029: Mean of Squared Errors = 9.97e+10
Epoch 030: Mean of Squared Errors = 9.09e+10
Epoch 031: Mean of Squared Errors = 8.31e+10
Epoch 032: Mean of Squared Errors = 7.63e+10
Epoch 033: Mean of Squared Errors = 7.02e+10
Epoch 034: Mean of Squared Errors = 6.48e+10
Epoch 035: Mean of Squared Errors = 6.01e+10
Epoch 036: Mean of Squared Errors = 5.59e+10
Epoch 037: Mean of Squared Errors = 5.22e+10
Epoch 038: Mean of Squared Errors = 4.90e+10
Epoch 039: Mean of Squared Errors = 4.61e+10
Epoch 040: Mean of Squared Errors = 4.35e+10
Epoch 041: Mean of Squared Errors = 4.13e+10
Epoch 042: Mean of Squared Errors = 3.93e+10
Epoch 043: Mean of Squared Errors = 3.75e+10
Epoch 044: Mean of Squared Errors = 3.60e+10
Epoch 045: Mean of Squared Errors = 3.46e+10
Epoch 046: Mean of Squared Errors = 3.34e+10
Epoch 047: Mean of Squared Errors = 3.23e+10
Epoch 048: Mean of Squared Errors = 3.14e+10
Epoch 049: Mean of Squared Errors = 3.05e+10
Epoch 050: Mean of Squared Errors = 2.98e+10
Epoch 051: Mean of Squared Errors = 2.91e+10
Epoch 052: Mean of Squared Errors = 2.85e+10
Epoch 053: Mean of Squared Errors = 2.80e+10
Epoch 054: Mean of Squared Errors = 2.76e+10
Epoch 055: Mean of Squared Errors = 2.72e+10
Epoch 056: Mean of Squared Errors = 2.68e+10
Epoch 057: Mean of Squared Errors = 2.65e+10
Epoch 058: Mean of Squared Errors = 2.62e+10
Epoch 059: Mean of Squared Errors = 2.60e+10
Epoch 060: Mean of Squared Errors = 2.58e+10
Epoch 061: Mean of Squared Errors = 2.56e+10
Epoch 062: Mean of Squared Errors = 2.54e+10
Epoch 063: Mean of Squared Errors = 2.53e+10
Epoch 064: Mean of Squared Errors = 2.52e+10
Epoch 065: Mean of Squared Errors = 2.50e+10
Epoch 066: Mean of Squared Errors = 2.49e+10
Epoch 067: Mean of Squared Errors = 2.48e+10
Epoch 068: Mean of Squared Errors = 2.48e+10
Epoch 069: Mean of Squared Errors = 2.47e+10
Epoch 070: Mean of Squared Errors = 2.46e+10
Epoch 071: Mean of Squared Errors = 2.46e+10
Epoch 072: Mean of Squared Errors = 2.45e+10
Epoch 073: Mean of Squared Errors = 2.45e+10
Epoch 074: Mean of Squared Errors = 2.44e+10
Epoch 075: Mean of Squared Errors = 2.44e+10
Epoch 076: Mean of Squared Errors = 2.44e+10
Epoch 077: Mean of Squared Errors = 2.44e+10
Epoch 078: Mean of Squared Errors = 2.43e+10
Epoch 079: Mean of Squared Errors = 2.43e+10
Epoch 080: Mean of Squared Errors = 2.43e+10
Epoch 081: Mean of Squared Errors = 2.43e+10
Epoch 082: Mean of Squared Errors = 2.43e+10
Epoch 083: Mean of Squared Errors = 2.43e+10
Epoch 084: Mean of Squared Errors = 2.42e+10
Epoch 085: Mean of Squared Errors = 2.42e+10
Epoch 086: Mean of Squared Errors = 2.42e+10
Epoch 087: Mean of Squared Errors = 2.42e+10
Epoch 088: Mean of Squared Errors = 2.42e+10
Epoch 089: Mean of Squared Errors = 2.42e+10
Epoch 090: Mean of Squared Errors = 2.42e+10
Epoch 091: Mean of Squared Errors = 2.42e+10
Epoch 092: Mean of Squared Errors = 2.42e+10
Epoch 093: Mean of Squared Errors = 2.42e+10
Epoch 094: Mean of Squared Errors = 2.42e+10
Epoch 095: Mean of Squared Errors = 2.42e+10
Epoch 096: Mean of Squared Errors = 2.42e+10
Epoch 097: Mean of Squared Errors = 2.42e+10
Epoch 098: Mean of Squared Errors = 2.42e+10
Epoch 099: Mean of Squared Errors = 2.42e+10
Epoch 100: Mean of Squared Errors = 2.42e+10
Epoch 101: Mean of Squared Errors = 2.42e+10
Epoch 102: Mean of Squared Errors = 2.42e+10
Epoch 103: Mean of Squared Errors = 2.42e+10
Epoch 104: Mean of Squared Errors = 2.42e+10
Epoch 105: Mean of Squared Errors = 2.42e+10
Epoch 106: Mean of Squared Errors = 2.42e+10
Epoch 107: Mean of Squared Errors = 2.42e+10
Epoch 108: Mean of Squared Errors = 2.42e+10
Epoch 109: Mean of Squared Errors = 2.42e+10
Epoch 110: Mean of Squared Errors = 2.42e+10
Epoch 111: Mean of Squared Errors = 2.42e+10
Epoch 112: Mean of Squared Errors = 2.42e+10
Epoch 113: Mean of Squared Errors = 2.42e+10
Epoch 114: Mean of Squared Errors = 2.42e+10
Epoch 115: Mean of Squared Errors = 2.42e+10
Epoch 116: Mean of Squared Errors = 2.42e+10
Epoch 117: Mean of Squared Errors = 2.42e+10
Epoch 118: Mean of Squared Errors = 2.42e+10
Epoch 119: Mean of Squared Errors = 2.42e+10
Epoch 120: Mean of Squared Errors = 2.42e+10
Epoch 121: Mean of Squared Errors = 2.42e+10
Epoch 122: Mean of Squared Errors = 2.42e+10
Epoch 123: Mean of Squared Errors = 2.42e+10
Epoch 124: Mean of Squared Errors = 2.42e+10
Epoch 125: Mean of Squared Errors = 2.42e+10
Epoch 126: Mean of Squared Errors = 2.42e+10
Epoch 127: Mean of Squared Errors = 2.42e+10
Epoch 128: Mean of Squared Errors = 2.42e+10
Epoch 129: Mean of Squared Errors = 2.42e+10
Epoch 130: Mean of Squared Errors = 2.42e+10
Epoch 131: Mean of Squared Errors = 2.42e+10
Epoch 132: Mean of Squared Errors = 2.42e+10
Epoch 133: Mean of Squared Errors = 2.42e+10
Epoch 134: Mean of Squared Errors = 2.42e+10
Epoch 135: Mean of Squared Errors = 2.42e+10
Epoch 136: Mean of Squared Errors = 2.42e+10
Epoch 137: Mean of Squared Errors = 2.42e+10
Epoch 138: Mean of Squared Errors = 2.42e+10
Epoch 139: Mean of Squared Errors = 2.42e+10
Epoch 140: Mean of Squared Errors = 2.42e+10
Epoch 141: Mean of Squared Errors = 2.42e+10
Epoch 142: Mean of Squared Errors = 2.42e+10
Epoch 143: Mean of Squared Errors = 2.42e+10
Epoch 144: Mean of Squared Errors = 2.42e+10
Epoch 145: Mean of Squared Errors = 2.42e+10
Epoch 146: Mean of Squared Errors = 2.42e+10
Epoch 147: Mean of Squared Errors = 2.42e+10
Epoch 148: Mean of Squared Errors = 2.42e+10
Epoch 149: Mean of Squared Errors = 2.42e+10
Epoch 150: Mean of Squared Errors = 2.42e+10
Epoch 151: Mean of Squared Errors = 2.42e+10
Epoch 152: Mean of Squared Errors = 2.42e+10
Epoch 153: Mean of Squared Errors = 2.42e+10
Epoch 154: Mean of Squared Errors = 2.42e+10
Epoch 155: Mean of Squared Errors = 2.42e+10
Epoch 156: Mean of Squared Errors = 2.42e+10
Epoch 157: Mean of Squared Errors = 2.42e+10
Epoch 158: Mean of Squared Errors = 2.42e+10
Epoch 159: Mean of Squared Errors = 2.42e+10
Epoch 160: Mean of Squared Errors = 2.42e+10
Epoch 161: Mean of Squared Errors = 2.42e+10
Epoch 162: Mean of Squared Errors = 2.42e+10
Epoch 163: Mean of Squared Errors = 2.42e+10
Epoch 164: Mean of Squared Errors = 2.42e+10
Epoch 165: Mean of Squared Errors = 2.42e+10
Epoch 166: Mean of Squared Errors = 2.42e+10
Epoch 167: Mean of Squared Errors = 2.42e+10
Epoch 168: Mean of Squared Errors = 2.42e+10
Epoch 169: Mean of Squared Errors = 2.42e+10
Epoch 170: Mean of Squared Errors = 2.42e+10
Epoch 171: Mean of Squared Errors = 2.42e+10
Epoch 172: Mean of Squared Errors = 2.42e+10
Epoch 173: Mean of Squared Errors = 2.42e+10
Epoch 174: Mean of Squared Errors = 2.42e+10
Epoch 175: Mean of Squared Errors = 2.42e+10
Epoch 176: Mean of Squared Errors = 2.42e+10
Epoch 177: Mean of Squared Errors = 2.42e+10
Epoch 178: Mean of Squared Errors = 2.42e+10
Epoch 179: Mean of Squared Errors = 2.42e+10
Epoch 180: Mean of Squared Errors = 2.42e+10
Epoch 181: Mean of Squared Errors = 2.42e+10
Epoch 182: Mean of Squared Errors = 2.42e+10
Epoch 183: Mean of Squared Errors = 2.42e+10
Epoch 184: Mean of Squared Errors = 2.42e+10
Epoch 185: Mean of Squared Errors = 2.42e+10
Epoch 186: Mean of Squared Errors = 2.42e+10
Epoch 187: Mean of Squared Errors = 2.42e+10
Epoch 188: Mean of Squared Errors = 2.42e+10
Epoch 189: Mean of Squared Errors = 2.42e+10
Epoch 190: Mean of Squared Errors = 2.42e+10
Epoch 191: Mean of Squared Errors = 2.42e+10
Epoch 192: Mean of Squared Errors = 2.42e+10
Epoch 193: Mean of Squared Errors = 2.42e+10
Epoch 194: Mean of Squared Errors = 2.42e+10
Epoch 195: Mean of Squared Errors = 2.42e+10
Epoch 196: Mean of Squared Errors = 2.42e+10
Epoch 197: Mean of Squared Errors = 2.42e+10
Epoch 198: Mean of Squared Errors = 2.42e+10
Epoch 199: Mean of Squared Errors = 2.42e+10
Epoch 200: Mean of Squared Errors = 2.42e+10
Epoch 201: Mean of Squared Errors = 2.42e+10
Epoch 202: Mean of Squared Errors = 2.42e+10
Epoch 203: Mean of Squared Errors = 2.42e+10
Epoch 204: Mean of Squared Errors = 2.42e+10
Epoch 205: Mean of Squared Errors = 2.42e+10
Epoch 206: Mean of Squared Errors = 2.42e+10
Epoch 207: Mean of Squared Errors = 2.42e+10
Epoch 208: Mean of Squared Errors = 2.42e+10
Epoch 209: Mean of Squared Errors = 2.42e+10
Epoch 210: Mean of Squared Errors = 2.42e+10
Epoch 211: Mean of Squared Errors = 2.42e+10
Epoch 212: Mean of Squared Errors = 2.42e+10
Epoch 213: Mean of Squared Errors = 2.42e+10
Epoch 214: Mean of Squared Errors = 2.42e+10
Epoch 215: Mean of Squared Errors = 2.42e+10
Epoch 216: Mean of Squared Errors = 2.42e+10
Epoch 217: Mean of Squared Errors = 2.42e+10
Epoch 218: Mean of Squared Errors = 2.42e+10
Epoch 219: Mean of Squared Errors = 2.42e+10
Epoch 220: Mean of Squared Errors = 2.42e+10
Epoch 221: Mean of Squared Errors = 2.42e+10
Epoch 222: Mean of Squared Errors = 2.42e+10
Epoch 223: Mean of Squared Errors = 2.42e+10
Epoch 224: Mean of Squared Errors = 2.42e+10
Epoch 225: Mean of Squared Errors = 2.42e+10
Epoch 226: Mean of Squared Errors = 2.42e+10
Epoch 227: Mean of Squared Errors = 2.42e+10
Epoch 228: Mean of Squared Errors = 2.42e+10
Epoch 229: Mean of Squared Errors = 2.42e+10
Epoch 230: Mean of Squared Errors = 2.42e+10
Epoch 231: Mean of Squared Errors = 2.42e+10
Epoch 232: Mean of Squared Errors = 2.42e+10
Epoch 233: Mean of Squared Errors = 2.42e+10
Epoch 234: Mean of Squared Errors = 2.42e+10
Epoch 235: Mean of Squared Errors = 2.42e+10
Epoch 236: Mean of Squared Errors = 2.42e+10
Epoch 237: Mean of Squared Errors = 2.42e+10
Epoch 238: Mean of Squared Errors = 2.42e+10
Epoch 239: Mean of Squared Errors = 2.42e+10
Epoch 240: Mean of Squared Errors = 2.42e+10
Epoch 241: Mean of Squared Errors = 2.42e+10
Epoch 242: Mean of Squared Errors = 2.42e+10
Epoch 243: Mean of Squared Errors = 2.42e+10
Epoch 244: Mean of Squared Errors = 2.42e+10
Epoch 245: Mean of Squared Errors = 2.42e+10
Epoch 246: Mean of Squared Errors = 2.42e+10
Epoch 247: Mean of Squared Errors = 2.42e+10
Epoch 248: Mean of Squared Errors = 2.42e+10
Epoch 249: Mean of Squared Errors = 2.42e+10
Epoch 250: Mean of Squared Errors = 2.42e+10
Epoch 251: Mean of Squared Errors = 2.42e+10
Epoch 252: Mean of Squared Errors = 2.42e+10
Epoch 253: Mean of Squared Errors = 2.42e+10
Epoch 254: Mean of Squared Errors = 2.42e+10
Epoch 255: Mean of Squared Errors = 2.42e+10
Epoch 256: Mean of Squared Errors = 2.42e+10
Epoch 257: Mean of Squared Errors = 2.42e+10
Epoch 258: Mean of Squared Errors = 2.42e+10
Epoch 259: Mean of Squared Errors = 2.42e+10
Epoch 260: Mean of Squared Errors = 2.42e+10
Epoch 261: Mean of Squared Errors = 2.42e+10
Epoch 262: Mean of Squared Errors = 2.42e+10
Epoch 263: Mean of Squared Errors = 2.42e+10
Epoch 264: Mean of Squared Errors = 2.42e+10
Epoch 265: Mean of Squared Errors = 2.42e+10
Epoch 266: Mean of Squared Errors = 2.42e+10
Epoch 267: Mean of Squared Errors = 2.42e+10
Epoch 268: Mean of Squared Errors = 2.42e+10
Epoch 269: Mean of Squared Errors = 2.42e+10
Epoch 270: Mean of Squared Errors = 2.42e+10
Epoch 271: Mean of Squared Errors = 2.42e+10
Epoch 272: Mean of Squared Errors = 2.42e+10
Epoch 273: Mean of Squared Errors = 2.42e+10
Epoch 274: Mean of Squared Errors = 2.42e+10
Epoch 275: Mean of Squared Errors = 2.42e+10
Epoch 276: Mean of Squared Errors = 2.42e+10
Epoch 277: Mean of Squared Errors = 2.42e+10
Epoch 278: Mean of Squared Errors = 2.42e+10
Epoch 279: Mean of Squared Errors = 2.42e+10
Epoch 280: Mean of Squared Errors = 2.42e+10
Epoch 281: Mean of Squared Errors = 2.42e+10
Epoch 282: Mean of Squared Errors = 2.42e+10
Epoch 283: Mean of Squared Errors = 2.42e+10
Epoch 284: Mean of Squared Errors = 2.42e+10
Epoch 285: Mean of Squared Errors = 2.42e+10
Epoch 286: Mean of Squared Errors = 2.42e+10
Epoch 287: Mean of Squared Errors = 2.42e+10
Epoch 288: Mean of Squared Errors = 2.42e+10
Epoch 289: Mean of Squared Errors = 2.42e+10
Epoch 290: Mean of Squared Errors = 2.42e+10
Epoch 291: Mean of Squared Errors = 2.42e+10
Epoch 292: Mean of Squared Errors = 2.42e+10
Epoch 293: Mean of Squared Errors = 2.42e+10
Epoch 294: Mean of Squared Errors = 2.42e+10
Epoch 295: Mean of Squared Errors = 2.42e+10
Epoch 296: Mean of Squared Errors = 2.42e+10
Epoch 297: Mean of Squared Errors = 2.42e+10
Epoch 298: Mean of Squared Errors = 2.42e+10
Epoch 299: Mean of Squared Errors = 2.42e+10
Epoch 300: Mean of Squared Errors = 2.42e+10
Epoch 301: Mean of Squared Errors = 2.42e+10
Epoch 302: Mean of Squared Errors = 2.42e+10
Epoch 303: Mean of Squared Errors = 2.42e+10
Epoch 304: Mean of Squared Errors = 2.42e+10
Epoch 305: Mean of Squared Errors = 2.42e+10
Epoch 306: Mean of Squared Errors = 2.42e+10
Epoch 307: Mean of Squared Errors = 2.42e+10
Epoch 308: Mean of Squared Errors = 2.42e+10
Epoch 309: Mean of Squared Errors = 2.42e+10
Epoch 310: Mean of Squared Errors = 2.42e+10
Epoch 311: Mean of Squared Errors = 2.42e+10
Epoch 312: Mean of Squared Errors = 2.42e+10
Epoch 313: Mean of Squared Errors = 2.42e+10
Epoch 314: Mean of Squared Errors = 2.42e+10
Epoch 315: Mean of Squared Errors = 2.42e+10
Epoch 316: Mean of Squared Errors = 2.42e+10
Epoch 317: Mean of Squared Errors = 2.42e+10
Epoch 318: Mean of Squared Errors = 2.42e+10
Epoch 319: Mean of Squared Errors = 2.42e+10
Epoch 320: Mean of Squared Errors = 2.42e+10
Epoch 321: Mean of Squared Errors = 2.42e+10
Epoch 322: Mean of Squared Errors = 2.42e+10
Epoch 323: Mean of Squared Errors = 2.42e+10
Epoch 324: Mean of Squared Errors = 2.42e+10
Epoch 325: Mean of Squared Errors = 2.42e+10
Epoch 326: Mean of Squared Errors = 2.42e+10
Epoch 327: Mean of Squared Errors = 2.42e+10
Epoch 328: Mean of Squared Errors = 2.42e+10
Epoch 329: Mean of Squared Errors = 2.42e+10
Epoch 330: Mean of Squared Errors = 2.42e+10
Epoch 331: Mean of Squared Errors = 2.42e+10
Epoch 332: Mean of Squared Errors = 2.42e+10
Epoch 333: Mean of Squared Errors = 2.42e+10
Epoch 334: Mean of Squared Errors = 2.42e+10
Epoch 335: Mean of Squared Errors = 2.42e+10
Epoch 336: Mean of Squared Errors = 2.42e+10
Epoch 337: Mean of Squared Errors = 2.42e+10
Epoch 338: Mean of Squared Errors = 2.42e+10
Epoch 339: Mean of Squared Errors = 2.42e+10
Epoch 340: Mean of Squared Errors = 2.42e+10
Epoch 341: Mean of Squared Errors = 2.42e+10
Epoch 342: Mean of Squared Errors = 2.42e+10
Epoch 343: Mean of Squared Errors = 2.42e+10
Epoch 344: Mean of Squared Errors = 2.42e+10
Epoch 345: Mean of Squared Errors = 2.42e+10
Epoch 346: Mean of Squared Errors = 2.42e+10
Epoch 347: Mean of Squared Errors = 2.42e+10
Epoch 348: Mean of Squared Errors = 2.42e+10
Epoch 349: Mean of Squared Errors = 2.42e+10
Epoch 350: Mean of Squared Errors = 2.42e+10
Epoch 351: Mean of Squared Errors = 2.42e+10
Epoch 352: Mean of Squared Errors = 2.42e+10
Epoch 353: Mean of Squared Errors = 2.42e+10
Epoch 354: Mean of Squared Errors = 2.42e+10
Epoch 355: Mean of Squared Errors = 2.42e+10
Epoch 356: Mean of Squared Errors = 2.42e+10
Epoch 357: Mean of Squared Errors = 2.42e+10
Epoch 358: Mean of Squared Errors = 2.42e+10
Epoch 359: Mean of Squared Errors = 2.42e+10
Epoch 360: Mean of Squared Errors = 2.42e+10
Epoch 361: Mean of Squared Errors = 2.42e+10
Epoch 362: Mean of Squared Errors = 2.42e+10
Epoch 363: Mean of Squared Errors = 2.42e+10
Epoch 364: Mean of Squared Errors = 2.42e+10
Epoch 365: Mean of Squared Errors = 2.42e+10
Epoch 366: Mean of Squared Errors = 2.42e+10
Epoch 367: Mean of Squared Errors = 2.42e+10
Epoch 368: Mean of Squared Errors = 2.42e+10
Epoch 369: Mean of Squared Errors = 2.42e+10
Epoch 370: Mean of Squared Errors = 2.42e+10
Epoch 371: Mean of Squared Errors = 2.42e+10
Epoch 372: Mean of Squared Errors = 2.42e+10
Epoch 373: Mean of Squared Errors = 2.42e+10
Epoch 374: Mean of Squared Errors = 2.42e+10
Epoch 375: Mean of Squared Errors = 2.42e+10
Epoch 376: Mean of Squared Errors = 2.42e+10
Epoch 377: Mean of Squared Errors = 2.42e+10
Epoch 378: Mean of Squared Errors = 2.42e+10
Epoch 379: Mean of Squared Errors = 2.42e+10
Epoch 380: Mean of Squared Errors = 2.42e+10
Epoch 381: Mean of Squared Errors = 2.42e+10
Epoch 382: Mean of Squared Errors = 2.42e+10
Epoch 383: Mean of Squared Errors = 2.42e+10
Epoch 384: Mean of Squared Errors = 2.42e+10
Epoch 385: Mean of Squared Errors = 2.42e+10
Epoch 386: Mean of Squared Errors = 2.42e+10
Epoch 387: Mean of Squared Errors = 2.42e+10
Epoch 388: Mean of Squared Errors = 2.42e+10
Epoch 389: Mean of Squared Errors = 2.42e+10
Epoch 390: Mean of Squared Errors = 2.42e+10
Epoch 391: Mean of Squared Errors = 2.42e+10
Epoch 392: Mean of Squared Errors = 2.42e+10
Epoch 393: Mean of Squared Errors = 2.42e+10
Epoch 394: Mean of Squared Errors = 2.42e+10
Epoch 395: Mean of Squared Errors = 2.42e+10
Epoch 396: Mean of Squared Errors = 2.42e+10
Epoch 397: Mean of Squared Errors = 2.42e+10
Epoch 398: Mean of Squared Errors = 2.42e+10
Epoch 399: Mean of Squared Errors = 2.42e+10
Epoch 400: Mean of Squared Errors = 2.42e+10
Epoch 401: Mean of Squared Errors = 2.42e+10
Epoch 402: Mean of Squared Errors = 2.42e+10
Epoch 403: Mean of Squared Errors = 2.42e+10
Epoch 404: Mean of Squared Errors = 2.42e+10
Epoch 405: Mean of Squared Errors = 2.42e+10
Epoch 406: Mean of Squared Errors = 2.42e+10
Epoch 407: Mean of Squared Errors = 2.42e+10
Epoch 408: Mean of Squared Errors = 2.42e+10
Epoch 409: Mean of Squared Errors = 2.42e+10
Epoch 410: Mean of Squared Errors = 2.42e+10
Epoch 411: Mean of Squared Errors = 2.42e+10
Epoch 412: Mean of Squared Errors = 2.42e+10
Epoch 413: Mean of Squared Errors = 2.42e+10
Epoch 414: Mean of Squared Errors = 2.42e+10
Epoch 415: Mean of Squared Errors = 2.42e+10
Epoch 416: Mean of Squared Errors = 2.42e+10
Epoch 417: Mean of Squared Errors = 2.42e+10
Epoch 418: Mean of Squared Errors = 2.42e+10
Epoch 419: Mean of Squared Errors = 2.42e+10
Epoch 420: Mean of Squared Errors = 2.42e+10
Epoch 421: Mean of Squared Errors = 2.42e+10
Epoch 422: Mean of Squared Errors = 2.42e+10
Epoch 423: Mean of Squared Errors = 2.42e+10
Epoch 424: Mean of Squared Errors = 2.42e+10
Epoch 425: Mean of Squared Errors = 2.42e+10
Epoch 426: Mean of Squared Errors = 2.42e+10
Epoch 427: Mean of Squared Errors = 2.42e+10
Epoch 428: Mean of Squared Errors = 2.42e+10
Epoch 429: Mean of Squared Errors = 2.42e+10
Epoch 430: Mean of Squared Errors = 2.42e+10
Epoch 431: Mean of Squared Errors = 2.42e+10
Epoch 432: Mean of Squared Errors = 2.42e+10
Epoch 433: Mean of Squared Errors = 2.42e+10
Epoch 434: Mean of Squared Errors = 2.42e+10
Epoch 435: Mean of Squared Errors = 2.42e+10
Epoch 436: Mean of Squared Errors = 2.42e+10
Epoch 437: Mean of Squared Errors = 2.42e+10
Epoch 438: Mean of Squared Errors = 2.42e+10
Epoch 439: Mean of Squared Errors = 2.42e+10
Epoch 440: Mean of Squared Errors = 2.42e+10
Epoch 441: Mean of Squared Errors = 2.42e+10
Epoch 442: Mean of Squared Errors = 2.42e+10
Epoch 443: Mean of Squared Errors = 2.42e+10
Epoch 444: Mean of Squared Errors = 2.42e+10